AllCops:
  TargetRubyVersion: 2.7
  AllowSymlinksInCacheRootDirectory: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: key

Layout/EndOfLine:
  EnforcedStyle: lf

Lint/ConstantDefinitionInBlock:
  Exclude:
  - spec/**/*_spec.rb

Metrics/AbcSize:
  Max: 60

Metrics/BlockLength:
  Max: 90

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/LineLength:
  Max: 180 # we're not in the 80s anymore.

Metrics/ModuleLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Style/FormatString:
  EnforcedStyle: percent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  ConsistentQuotesInMultiline: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
