source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef'
gem 'chefspec', '>= 7.1'
gem 'fauxhai', '>= 2.2'
gem 'foodcritic', '>= 4.0'
gem 'kitchen-ec2', '>= 2.0.0'
gem 'rake'
gem 'rspec'
gem 'rubocop', '~> 1.25'
gem 'test-kitchen', '>= 2.5.0'
