name             'wsus-client-test'
maintainer       'Criteo'
maintainer_email 'b.courtois@criteo.com'
license          'Apache-2.0'
description      'Test cookbook for wsus-client'
version          '0.1.0'
supports         'windows'
depends          'wsus-client'
